### ISSUE TITLE
Error when including Image as a survey question

### ISSUE THREAD

**Issue by akshay-vaidya** [SurveyMonkey/public_api_docs#58]
I am trying to include an image as a survey question and it gives be the below error,
![selection_003](https://user-images.githubusercontent.com/14146528/27974835-8aefd3ea-6357-11e7-80eb-d7d0145e402a.png)

I am using the below JSON code ,
 payload ={
    "headings": [
        {
            "heading": "This is a monkey",
            "image": {
                "img_url": "https://raw.githubusercontent.com/SurveyMonkey/public_api_docs/master/images/presentation.png"
            }
        }
    ],
    "position": 4,
    "family": "presentation",
    "subtype": "descriptive_text"
}

Kindly help!

**Comment by adamklockars** [comment]
One of your keys is incorrect. `image_url` not `img_url`.
`{
    "headings": [
        {
            "heading": "This is a monkey",
            "image": {
                "image_url": "http://surveymonkey.com/monkey.jpg"
            }
        }
    ],
    "position": 1,
    "family": "presentation",
    "subtype": "descriptive_text"
}`

**Comment by akshay-vaidya** [comment]
@adamklockars 

I am getting the same error.
![selection_003](https://user-images.githubusercontent.com/14146528/27976643-5c5cd390-635f-11e7-8e84-75cf326d917f.png)

**Comment by adamklockars** [comment]
Our docs were way off. Sorry about that.
`{ "headings": [ { "heading": "This is a monkey", "image": { "url": "http://surveymonkey.com/monkey.jpg" } } ], "position": 1, "family": "presentation", "subtype": "image" }`

**Comment by akshay-vaidya** [comment]
@adamklockars  It works thanks!

**Comment by akshay-vaidya** [comment]
@adamklockars  I tried adding "answers" option for the image question, I used the below code.

payload ={ "headings": [ 
{ "heading": "What monkey is this?", "image": { "url": "https://raw.githubusercontent.com/SurveyMonkey/public_api_docs/master/images/presentation.png" } } ], "position": 1, "family": "single_choice", "subtype": "vertical",    "answers": {
        "choices":[
            {
                "text": "Capuchin"
            },
            {
                "text": "Mandrill"
            },
        ],
        "other":[
                {
                    "text": "Other",
                    "num_chars": 100,
                    "num_lines": 3
                }
        ]
    } }


This doesn't seem to work. I don't see any information about this in the docs as well.

**Comment by adamklockars** [comment]
@akshay-vaidya Unfortunately, images can only be inserted into a survey with the image type question (family: presentation, subtype: image).

**Comment by akshay-vaidya** [comment]
@adamklockars Alright. Can I constrain the size of the image being uploaded?

**Comment by adamklockars** [comment]
@akshay-vaidya No. Neither the SurveyMonkey UI or API allow you to adjust the size of the image in the question at this time.

**Comment by akshay-vaidya** [comment]
@adamklockars Thanks Adam, for clarification. I also wanted to know how to upload image from local using the "payload" JSON script. When I tried doing that I am getting the below error,
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=4032x3024 at 0x7FD0E8DD5680> is not JSON serializable
