### ISSUE TITLE
Error- "Star rating" Questions

### ISSUE THREAD

**Issue by akshay-vaidya** [SurveyMonkey/public_api_docs#60]
I executed the below script to generate star rating 

payload={
    "headings": [
        {
            "heading": "How many stars on the walk of fame should monkeys have?"
        }
    ],
    "position": 1,
    "family": "matrix",
    "subtype": "rating",
    "display_options": {
        "display_type": "emoji",
        "display_subtype": "star"
    },
    "forced_ranking": "false",
    "answers":{
    "rows": [
      {
        "visible": "true",
        "text": "",
        "position": 1
      }
    ],
    "choices": [
      {
        "weight": 1,
        "text": ""
      },
      {
        "weight": 2,
        "text": ""
      },
      {
        "weight": 3,
        "text": ""
      },
      {
        "weight": 4,
        "text": ""
      },
      {
        "weight": 5,
        "text": ""
      }
    ]
  }
}

And I am getting the below error:
u'message': u"Value 0 for field 'forced_ranking' is not of type boolean"

**Comment by adamklockars** [comment]
@akshay-vaidya Remove the quotes around the boolean values (forced_ranking, visible). The quotes do not exist in the docs.

**Comment by akshay-vaidya** [comment]
@adamklockars 
Without quotes I am getting the below error,
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
NameError: name 'false' is not defined

**Comment by adamklockars** [comment]
Try False, not false.

**Comment by akshay-vaidya** [comment]
@adamklockars. Thanks.. That works!

**Comment by adamklockars** [comment]
@akshay-vaidya If you have anymore SurveyMonkey API questions that are not doc related issues, create a Stackoverflow question with the #surveymonkey tag (https://stackoverflow.com/questions/tagged/surveymonkey), and we'll be happy to help out.

**Comment by akshay-vaidya** [comment]
@adamklockars I am wondering if there is a way to mark a question "required" (requires answer). I found an option mentioned in the doc but that doesn't seem to work. Find the code below,

payload2={
    "headings": [
        {
            "heading": "5. Does the image make you feel positive?"
        }
    ],
    "position": 1,
    "family": "single_choice",
    "subtype": "vertical",
    "required": {
	"text": "Require an answer to this question",
	"amount": "1",
	"type" : "exactly"
		},
    "answers": {
        "choices":[
            {
                "text": "Strongly Disagree"
            },
            {
                "text": "Disagree"
            },
            {
                "text": "Neutral"
            },
            {
                "text": "Agree"
            },
            {
                "text": "Strongly Agree"
            }
        ]

    }
}

I am getting the below response,

![image](https://user-images.githubusercontent.com/14146528/28163523-681ca17a-67c3-11e7-848b-4e1a23336c10.png)

KIndly help.

**Comment by adamklockars** [comment]
@akshay-vaidya Sorry for the delay in my response. I was on vacation during the end of last week.
Try the following:
`{
"headings": [
{
"heading": "5. Does the image make you feel positive?"
}
],
"position": 1,
"family": "single_choice",
"subtype": "vertical",
"required": {
"text": "Require an answer to this question",
"amount": "0",
"type" : "all"
},
"answers": {
"choices":[
{
"text": "Strongly Disagree"
},
{
"text": "Disagree"
},
{
"text": "Neutral"
},
{
"text": "Agree"
},
{
"text": "Strongly Agree"
}
]

}
}`
I'll have the docs updated.

**Comment by akshay-vaidya** [comment]
@adamklockars I have 116 surveys created in my account. I wanted to know if there is any way to extract the responses of all the surveys in a single csv file?

Thanks!

**Comment by adamklockars** [comment]
@akshay-vaidya There is no built in way to accomplish this via the API or UI for that matter. Unless all your surveys are identical, I'm not sure what your trying to achieve by creating a single CSV. If you are able to further define your use case, please do so via a Stackoverflow question with the #surveymonkey tag (https://stackoverflow.com/questions/tagged/surveymonkey), and we'll be happy to help out.

**Comment by akshay-vaidya** [comment]
@adamklockars All the surveys have 50 similar questions with different image presented. It would be easy for us to analyze when we get the responses consolidated.
