### ISSUE TITLE
 https://developer.surveymonkey.net/integrations/ not working

### ISSUE THREAD

**Issue by akshay-vaidya** [SurveyMonkey/public_api_docs#61]
Receiving 404 error for this link today, when will it be back as we can longer access our Apps ?
We would need API keys to generate surveys.
Account is briankiefel and we are paying for the service on SELECT monthly plan.

Kindly help!

**Comment by adamklockars** [comment]
@akshay-vaidya The issue was resolved earlier today. Please don't open issues against this repo for issues that are not documentation related. Instead contact api-support@surveymonkey.com
